Laundry/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('', views.landing, name='landing'),
    path('add-service/', views.add_service, name='add-service'),
    path('add-to-cart/', views.add_to_cart, name='add-to-cart'),
    path('about/', views.about, name='about'), 
    path('add-services-to-cart/', views.add_services_to_cart, name='add-services-to-cart'),
    path('delete-service-from-cart/<int:pk>/', views.delete_service_from_cart, name='delete-service-from-cart'),
    path('check-out-here/', views.checkout_here, name='checkout-here'),
    path('pay-for-laundry/', views.pay_for_laundry, name='pay-for-laundry')
]

django_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('Laundry.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('payment/', include('payment.urls'))
]

users/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('register/', views.register_user, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
]

Laundry/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Service(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    price = models.PositiveIntegerField()

    def __str__(self):
        return self.name
    
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    clothes_amount = models.PositiveIntegerField(default=1)
    is_verified = models.BooleanField(default=False)
    total_amount = models.PositiveIntegerField(null=True, blank=True)

class ServiceCart(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Checkout(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=233)
    email_id = models.EmailField(max_length=255)
    delivery_address = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=10)
    timestamp = models.DateTimeField(auto_now_add=True)

Laundry/forms.py
from django import forms

from .models import Cart, Checkout, Service, ServiceCart


class AddServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ['name', 'price']

class AddToCartForm(forms.ModelForm):
    class Meta:
        model = Cart
        fields = ['clothes_amount']

class AddServiceToCartForm(forms.ModelForm):
    class Meta:
        model = ServiceCart
        fields = ['service']

class CheckOutForm(forms.ModelForm):
    class Meta:
        model = Checkout
        fields = ['full_name', 'email_id', 'delivery_address','phone_number']

Laundry/views.py
from django.contrib import messages
from django.db.models import Sum
from django.shortcuts import redirect, render

from payment.models import Wallet

from .forms import AddServiceForm, AddServiceToCartForm, AddToCartForm, CheckOutForm
from .models import Cart, Checkout, ServiceCart


def home(request):
    context = {}
    return render(request, 'laundry/home.html', context)

def landing(request):
    context = {}
    return render(request, 'laundry/landing.html', context)

def about(request):
    context = {}
    return render(request, 'laundry/about.html', context)

def add_service(request):
    if request.method == 'POST':
        form = AddServiceForm(request.POST)
        if form.is_valid():
            service = form.save(commit=False)
            service.user = request.user
            service.save()
            messages.success(request, 'New service added successfully!')
            return redirect('add-service')
        else:
            messages.warning(request, 'Sorry, something went wrong.')
            return redirect('add-service')

    else:
        form = AddServiceForm()
        context = {'form': form}
        return render(request, 'laundry/add_service.html', context)


def add_to_cart(request):
    if request.method == 'POST':
        form = AddToCartForm(request.POST)
        if form.is_valid():
            cart_item = form.save(commit=False)
            cart_item.user = request.user
            cart_item.save()
            request.session['cart_id'] = cart_item.id
            return redirect('add-services-to-cart')
        else:
            messages.warning(request, 'Sorry, Something went wrong!')
            return redirect('add-to-cart')
        
    else:
        form = AddToCartForm()
        context = {'form': form}
        return render(request, 'laundry/add_to_cart.html', context)

def add_services_to_cart(request):
    if request.method == 'POST':
        form = AddServiceToCartForm(request.POST)
        if form.is_valid():
            service_cart_item = form.save(commit=False)
            service_cart_item.user = request.user
            cart = Cart.objects.get(id=request.session['cart_id'])
            service_cart_item.cart = cart
            service_cart_item.save()
            messages.info(request, 'A service has been added to your cart')
            return redirect('add-services-to-cart')
        else:
            print(form.errors)
            messages.warning(request, 'Something went wrong')
            return redirect('add-services-to-cart')

    else:
        form = AddServiceToCartForm()
        cart = Cart.objects.get(id=request.session['cart_id'])
        get_obj = ServiceCart.objects.filter(cart=cart)
        
        # Calculate the total amount
        total_amount = get_obj.aggregate(Sum('service__price'))['service__price__sum']
        cart.total_amount = total_amount or 0
        cart.save()
        
        context = {'form': form, 'get_obj': get_obj, 'cart':cart}
        return render(request, 'laundry/add_service_to_cart.html', context)

def delete_service_from_cart(request, pk):
    service_cart_item = ServiceCart.objects.get(pk=pk)
    service_cart_item.delete()

    cart = Cart.objects.get(id=request.session['cart_id'])
    get_obj = ServiceCart.objects.filter(cart=cart)
    count = 0
    for obj in get_obj:
        calc = obj.service.price * cart.clothes_amount
        count += calc
    cart.total_amount = count
    cart.save()
    return redirect('add-services-to-cart')

def checkout_here(request):
    if request.method == 'POST':
        form = CheckOutForm(request.POST)
        if form.is_valid():
            var = form.save(commit=False)
            cart_id = request.session['cart_id']
            cart = Cart.objects.get(id=cart_id)
            var.cart = cart
            var.save()
            context = {'cart':cart}
            return render(request, 'payment/make_payment_from_wallet.html')
        else:
            messages.warning(request, 'Something went wrong')
            return redirect('checkout-here')
    else:
        form = CheckOutForm()
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        get_obj = ServiceCart.objects.filter(cart=cart)
        context = {'form': form, 'cart': cart, 'get_obj': get_obj}
        return render(request, 'laundry/checkout_here.html', context)
     
def pay_for_laundry(request):
    cart = Cart.objects.get(id=request.session['cart_id'])
    wallet = Wallet.objects.get(user=request.user)
    print(cart.total_amount)
    
    if wallet.balance >= cart.total_amount:
        wallet.balance -= cart.total_amount
        cart.is_verified = True
        cart.save()
        wallet.save()
        messages.info(request, 'Payment completed! Laundry process has been initiated')
        return redirect('home')
    else:
        messages.warning(request, 'Sorry, insufficient funds in your wallet!')
        return redirect('add-services-to-cart')

templates/laundry/about.html
{% extends 'users/base.html' %}
{% load static %}
{% block content %}
  <div class="container">
    <h1>About Us</h1>
    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tristique lorem ut sapien semper dignissim. Sed hendrerit leo sit amet risus eleifend, ac fermentum ex ultrices. Maecenas ac eleifend velit. Fusce fringilla dui risus, vel facilisis lectus ultricies vel. Ut consectetur libero lectus, ut aliquet enim consectetur ac. Nam quis mauris vel enim fringilla tincidunt eu ut tortor. Nulla facilisi. Nullam varius justo vitae aliquet venenatis.</p>
    
    <h2>Our Mission</h2>
    <p>Our mission is to provide high-quality laundry services with convenience and reliability. We aim to make the laundry process effortless for our customers, ensuring their clothes are clean, fresh, and well-cared for. We strive to exceed customer expectations and deliver exceptional service.</p>

    <h2>Why Choose Us?</h2>
    <ul>
      <li>Convenient online service - Place your laundry order online from the comfort of your home.</li>
      <li>High-quality cleaning - We use advanced techniques and eco-friendly products to ensure excellent results.</li>
      <li>Fast turnaround - We offer quick turnaround times to ensure your laundry is ready when you need it.</li>
      <li>Professional staff - Our experienced team of laundry experts is dedicated to providing top-notch service.</li>
      <li>Competitive pricing - We offer competitive prices without compromising on quality.</li>
    </ul>

    <h2>Contact Us</h2>
    <p>If you have any questions or inquiries, please feel free to reach out to us. We are here to assist you.</p>
    <p>Email: info@example.com</p>
    <p>Phone: 123-456-7890</p>
  </div>
{% endblock %}

templates/laundry/add_service.html
{% extends 'users/base.html' %}
{% load widget_tweaks %}
{% load statics %}
{% block content %}
<div class="row">
  <div class="col-md-6">
    <div class="card mx-auto" style="width: 40rem;">
      <div class="card-body">
        <h5 class="card-title mb-3">Add a Service</h5>
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-success mb-3" role="alert">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
        <form method="POST">
          {% csrf_token %}
          <div class="form-group mb-3">
            <label for="name">Name:</label>
            {% render_field form.name class="form-control" %}
          </div>
          <div class="form-group">
            <label for="price">Price:</label>
            {% render_field form.price class="form-control" %}
          </div>
          <button type="submit" class="btn btn-primary mt-4">Add Service</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/laundry/add_service_to_cart.html
<!-- Updated add_services_to_cart.html -->
{% extends 'users/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
  <div class="container">
    <div class="row mt-0">
      <div class="col-md-6 offset-md-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title mb-3">Choose Laundry Service</h5>
            {% if messages %}
              <div class="alert alert-success" role="alert">
                {% for message in messages %}
                  {{ message }}
                {% endfor %}
              </div>
            {% endif %}
            <form method="POST">
              {% csrf_token %}
              <div class="form-group mb-3">
                <label for="name">Choose a service</label>
                {% render_field form.service class="form-control" %}
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>
      </div>
    </div>
    {% if get_obj %}
    <div class="row mt-5">
      <div class="col-md-6 offset-md-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title mb-3">Services selected</h5>
            {% for obj in get_obj %}
              {% with service=obj.service %}
                <div class="alert alert-primary alert-dismissible fade show" role="alert">
                  {{ service.name }} (Price(KSH): {{ service.price }})
                  <a href="{% url 'delete-service-from-cart' obj.pk %}" type="button" class="btn-close" aria-label="Close"></a>
                </div>
              {% endwith %}
            {% endfor %}
            <p class="card-text">Total Amount for {{cart.clothes_amount|default:"0"}} clothe(s) is {{ cart.total_amount|default:"0" }}</p>
            <a href="{% url 'checkout-here' %}" class="btn btn-primary btn-block">Check Out</a>
          </div>
        </div>
      </div>
    </div>
    {% endif %}
  </div>
{% endblock %}

templates/laundry/add_to_cart.html
{% extends 'users/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
<div class="container">
  <div class="row mt-0">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title mb-3">Add Clothes to Laundry Basket</h5>
          {% if messages %}
            <div class="alert alert-success" role="alert">
              {% for message in messages %}
                {{ message }}
              {% endfor %}
            </div>
          {% endif %}
          <form method="POST">
            {% csrf_token %}
            <div class="form-group mb-3">
              <label for="name">Amount of Clothes</label>
              {% render_field form.clothes_amount class="form-control" %}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/laundry/checkout_here.html
{% extends 'users/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    
    <div class="form-group mb-4">
      <label for="id_full_name">Full Name:</label>
      <input type="text" class="form-control" id="id_full_name" name="full_name" required>
    </div>
    
    <div class="form-group mb-4">
      <label for="id_email_id">Email:</label>
      <input type="email" class="form-control" id="id_email_id" name="email_id" required>
    </div>
    
    <div class="form-group mb-4">
      <label for="id_delivery_address">Delivery Address:</label>
      <textarea class="form-control" id="id_delivery_address" name="delivery_address" required></textarea>
    </div>
    
    <div class="form-group mb-4">
      <label for="id_phone_number">Phone Number:</label>
      <input type="tel" class="form-control" id="id_phone_number" name="phone_number" required>
    </div>
    
    <button type="submit" class="btn btn-primary mt-3">Submit</button>
  </form>  
{% endblock %}

templates/laundry/home.html
{% extends 'users/base.html' %}
{% load static %}
{% block content %}
<div class="container mt-4">
  <div class="jumbotron text-center">
    <h1 class="display-4">Welcome to our Laundry Website</h1>
    <p class="lead">We provide high-quality laundry services at affordable prices.</p>
    <div class="mb-4">
      <a href="{% url 'add-to-cart' %}" class="btn btn-primary btn-lg">Start Laundry</a>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="card mb-3">
        <div class="card-body">
          <h2 class="card-title">About Us</h2>
          <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eu purus justo. Curabitur faucibus luctus aliquam. Proin vulputate nulla vel iaculis vestibulum. In non leo a lorem porttitor ultricies.</p>
          <a href="{% url 'about' %}" class="btn btn-secondary">Learn More</a>
        </div>
      </div>
    </div>
    {% if request.user.is_superuser %}
    <div class="col-md-6">
      <div class="card mb-3">
        <div class="card-body">
          <li class="nav-item">
            <a href="{% url 'initiate-payment' %}" class="btn btn-primary">Fund wallet</a>
          </li>
          <h2 class="card-title">Add a Service</h2>
          <form method="POST" action="{% url 'add-service' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Add Service</button>
          </form>
        </div>
      </div>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/laundry/landing.html
{% extends 'users/base.html' %}
{% load static %}
{% block content %}
  <section class="jumbotron text-center">
    <h1 class="display-4">Welcome to the Laundry Website</h1>
    <p class="lead">The best place to get your laundry done.</p>
    <a href="{% url 'login' %}" class="btn btn-primary btn-lg">Login</a>
    <a href="{% url 'register' %}" class="btn btn-secondary btn-lg">Register</a>
  </section>
{% endblock %}